version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  allow:
  - dependency-name: "*adevinta*"
  - dependency-name: "github.com/manelmontilla/cron"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
