dist: bionic
language: go
services:
  - docker
go:
  - 1.21.x
env:
  global:
    - INPUT_PLATFORM=linux/amd64  # ,linux/arm64
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulcan-crontinuous
script:
  - go install $(go list ./... | grep -v /vendor/)
  - go test -v $(go list ./... | grep -v /vendor/)
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/buildx.sh)'
